pipeline {
         agent any

         stages {
                 stage ('compile stage'){
                                    steps {
                                            echo 'Running build phase..'
        }


    } 
   
 }

}
